version: '3.8'
services:
  rest:
    build: Dockerfile.rest
    environment:
      DATABASE_TYPE: PostgreSQL 
      DB_CONNECTION_STRING: "Host=postgres;Database=yourapp;Username=youruser;Password=yourpassword"
    ports:
      - "5340:5340"
    depends_on:
      - postgres

  grpc:
    build: Dockerfile.grpc
    environment:
      DATABASE_TYPE: PostgreSQL 
      DB_CONNECTION_STRING: "Host=postgres;Database=yourapp;Username=youruser;Password=yourpassword"
    ports:
      - "5341:5341"
    depends_on:
      - postgres

  grpc_code_first:
    build: Dockerfile.grpcCodeFirst
    environment:
      DATABASE_TYPE: PostgreSQL 
      DB_CONNECTION_STRING: "Host=postgres;Database=yourapp;Username=youruser;Password=yourpassword"
    ports:
      - "5342:5342"
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourapp
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
#     volumes:
#       - ErpBackendData:/var/lib/postgresql/data

# volumes:
#   ErpBackendData:
