version: '3.8'
services:
  rest:
    build:
      context: .
      dockerfile: dockerfile.REST
    environment:
      DATABASE_TYPE: PostgreSQL 
      DB_CONNECTION_STRING: "Host=postgres;Database=yourapp;Username=youruser;Password=yourpassword"
    ports:
      - "5340:5340"
    depends_on:
      - postgres

  grpc:
    build:
      context: .
      dockerfile: dockerfile.gRPC
    environment:
      DATABASE_TYPE: PostgreSQL 
      DB_CONNECTION_STRING: "Host=postgres;Database=yourapp;Username=youruser;Password=yourpassword"
    ports:
      - "5341:5341"
    depends_on:
      - postgres

  grpc_code_first:
    build:
      context: .
      dockerfile: dockerfile.gRPCCodeFirst
    environment:
      DATABASE_TYPE: PostgreSQL 
      DB_CONNECTION_STRING: "Host=postgres;Database=yourapp;Username=youruser;Password=yourpassword"
    ports:
      - "5342:5342"
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourapp
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - ErpBackendData:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  ErpBackendData:
